######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 21 15:31:15 2017
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              Modules/CPU \
              Modules/Date \
              Modules/Name \
              Modules/Network \
              Modules/OS \
              Modules/Ram \
              Modules/Time
INCLUDEPATH += .

# Input
HEADERS += Modules/CPU/Cpu.hpp \
           Modules/Date/Date.hpp \
           Modules/Name/Name.hpp \
           Modules/Network/Net.hpp \
           Modules/OS/OS.hpp \
           Modules/Ram/Ram.hpp \
           Modules/Time/Time.hpp \
           ../../back/SysInfo.hpp \
           ../../back/CPU.hpp \
           ../../back/Memory.hpp \
           ../../back/Network.hpp \
           ../MonitorModule.hpp \
           ../MonitorDisplay.hpp \
           Application.hpp \

SOURCES += main.cpp \
           Modules/CPU/Cpu.cpp \
           Modules/Date/Date.cpp \
           Modules/Name/Name.cpp \
           Modules/Network/Net.cpp \
           Modules/OS/OS.cpp \
           Modules/Ram/Ram.cpp \
           Modules/Time/Time.cpp \
           ../../back/CPU.cpp \
           ../../back/SysInfo.cpp \
           ../../back/Network.cpp \
           ../../back/Memory.cpp \
           ../MonitorModule.cpp \
           ../MonitorDisplay.cpp \
           Application.cpp \

